=== Lipa27/ZJprojekt/jan_podlipny.xsd
<!-- Odkaz na github: -->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="nastaveni">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="prednastaveni" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="hra">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="jaz" name="jazyk"/>
                    <xs:element type="vypzap" name="napoveda"/>
                    <xs:element type="jednot1" name="jednotky_vzdalenosti"/>
                    <xs:element type="jednot2" name="jednotky_rychlosti"/>
                    <xs:element type="jednot3" name="jednotky_teploty"/>
                    <xs:element type="pohled" name="vychozi_pohled"/>
                  </xs:sequence>
                  <xs:attribute type="verz" name="verze" use="required"/>
                  <xs:attribute type="chars" name="uzivatelske_jmeno" use="required"/>
                  <xs:attribute type="vypzap" name="autolog" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="grafika">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="vypzap" name="antistropni_filtr"/>
                    <xs:element type="vypzap" name="vyhlazovani_hran"/>
                    <xs:element type="vypzap" name="extra_AA"/>
                    <xs:element name="detaily">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="kvalitky" name="kvalita_textur"/>
                          <xs:element type="kvalitky" name="kvalita_stinu"/>
                          <xs:element type="stupnice" name="vykreslovaci_rozliseni"/>
                          <xs:element type="stupnice" name="kvalita_mraku"/>
                          <xs:element type="stupnice" name="kvalita_terenu"/>
                          <xs:element type="stupnice" name="vzdalenost_vykreslovani"/>
                          <xs:element type="stupnice" name="kvalita_odlesku"/>
                          <xs:element type="stupnice" name="kvalita_odrazu_vody"/>
                          <xs:element type="stupnice" name="kvalita_fyziky"/>
                          <xs:element type="kvalitky" name="deformace_terenu"/>
                          <xs:element type="kvalitky" name="kvalita_stop_pasu"/>
                        </xs:sequence>
                        <xs:attribute type="kvalitky" name="kvalita_det" use="required"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="vypzap" name="stiny"/>
                    <xs:element type="vypzap" name="detaily_pobrezi"/>
                    <xs:element type="vypzap" name="efekt_vlneni"/>
                    <xs:element type="vypzap" name="detaily_vegetace"/>
                  </xs:sequence>
                  <xs:attribute type="rozlis" name="rozliseni" use="required"/>
                  <xs:attribute type="modik" name="mod" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="zvuk">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="stupniceh" name="hlasitost"/>
                    <xs:element type="stupniceh" name="hlasitost_efektu"/>
                    <xs:element type="stupniceh" name="hlasitost_motoru"/>
                    <xs:element type="stupniceh" name="hlasitost_strelby"/>
                    <xs:element type="stupniceh" name="hlasitost_komunikace"/>
                    <xs:element type="vypzap" name="zvuky_v_hangaru"/>
                  </xs:sequence>
                  <xs:attribute type="vypzap" name="zapnuto" use="required"/>
                  <xs:attribute type="kvalitky" name="kvalita_zvuk" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="rozhrani">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="vypzap" name="velke_pismo_menu"/>
                    <xs:element type="vypzap" name="rozhrani_s_gamepadem"/>
                    <xs:element type="barva" name="barva_zamerneho_krize"/>
                    <xs:element type="stupnice" name="velikost_zamerneho_krize"/>
                    <xs:element type="vypzap" name="filtr_konverzace"/>
                    <xs:element type="stupnice" name="velikost_ukaz_poskozeni"/>
                    <xs:element type="stupnice" name="velikost_takticke_mapy"/>
                    <xs:element type="vypzap" name="titulky"/>
                    <xs:element type="vypzap" name="predsazeni"/>
                    <xs:element type="vypzap" name="ukazatele_nepratel"/>
                    <xs:element type="vypzap" name="zobrazeni_poskozeni"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="idicko" name="id" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Nastevni omezeni -->
  <xs:simpleType name="vypzap"> <!-- Omezeni zapnuto/vypnuto -->
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="1"/>
    </xs:restriction>
  </xs:simpleType> 
  <xs:simpleType name="jaz"> <!-- Omezeni jazyka -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="Czech"/>
      <xs:enumeration value="English"/>
      <xs:enumeration value="Russian"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="chars"> <!-- Omezeni pismen -->
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9]{0,20}"/>  
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="jednot1"> <!-- Omezeni delky -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="Km"/>
      <xs:enumeration value="Mil"/>
    </xs:restriction>
  </xs:simpleType>
    <xs:simpleType name="jednot2"> <!-- Omezeni rychlosti -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="Km/h"/>
      <xs:enumeration value="Mil/h"/>
    </xs:restriction>
    </xs:simpleType>
  <xs:simpleType name="jednot3"> <!-- Omezeni teploty -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="C"/>
      <xs:enumeration value="F"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="pohled"> <!-- Omezeni pohledu -->
    <xs:restriction base="xs:string">
       <xs:enumeration value="venkovni"/>
       <xs:enumeration value="kabina"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="verz"> <!-- Omezeni verze -->
    <xs:restriction base="xs:string">
      <xs:pattern value="1.67.2.115"/>
      <xs:pattern value="1.67.1.75"/>
    </xs:restriction>
  </xs:simpleType> 
  <xs:simpleType name="kvalitky"> <!-- Omezeni kvality detailu -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="nizka"/>
      <xs:enumeration value="stredni"/>
      <xs:enumeration value="vysoka"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="stupnice"> <!-- Omezeni stupnice -->
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="2"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="stupniceh"> <!-- Omezeni stupnice hlasitosti -->
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="10"/>
    </xs:restriction>
  </xs:simpleType> 
  <xs:simpleType name="rozlis"> <!-- Omezeni rozliseni -->
    <xs:restriction base="xs:string">
    	<xs:enumeration value="800x600"/>
        <xs:enumeration value="1024x768"/>
        <xs:enumeration value="1600x900"/>
        <xs:enumeration value="1920x1080"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="modik"> <!-- Omezeni modu zobrazeni -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="Fullscreen"/>
      <xs:enumeration value="Okno"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="barva"> <!-- Omezeni barvy zamerovace -->
    <xs:restriction base="xs:string">
    	<xs:enumeration value="bila"/>
        <xs:enumeration value="cervena"/>
        <xs:enumeration value="zluta"/>
        <xs:enumeration value="modra"/>
    </xs:restriction>
  </xs:simpleType> 
  <xs:simpleType name="idicko"> <!-- Omezeni id -->
    <xs:restriction base="xs:string">
      <xs:pattern value="set[\d]"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Lipa27/ZJprojekt/jan_podlipny.xml
<?xml version="1.0" encoding="UTF-8"?> 
  <?xml-stylesheet type="text/xsl" href="jan_podlipny.xsl"?>
  <!-- Odkaz na github: https://github.com/ --> 

<nastaveni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="C:\Users\Podli\Desktop\jan_podlipny.xsd">
  <prednastaveni id="set1">
    <hra verze="1.67.2.115" uzivatelske_jmeno="Tanker1" autolog="1">
      <jazyk>Czech</jazyk>
      <napoveda>0</napoveda>
      <jednotky_vzdalenosti>Km</jednotky_vzdalenosti>
      <jednotky_rychlosti>Km/h</jednotky_rychlosti>
      <jednotky_teploty>C</jednotky_teploty>
      <vychozi_pohled>venkovni</vychozi_pohled>
    </hra>
    <grafika rozliseni="1024x768" mod="Fullscreen">
        <antistropni_filtr>1</antistropni_filtr>
        <vyhlazovani_hran>1</vyhlazovani_hran>
        <extra_AA>0</extra_AA>
      <detaily kvalita_det="stredni">
        <kvalita_textur>stredni</kvalita_textur>
        <kvalita_stinu>vysoka</kvalita_stinu>
        <vykreslovaci_rozliseni>1</vykreslovaci_rozliseni>
        <kvalita_mraku>1</kvalita_mraku>
        <kvalita_terenu>1</kvalita_terenu>
        <vzdalenost_vykreslovani>1.5</vzdalenost_vykreslovani>
        <kvalita_odlesku>0.9</kvalita_odlesku>
        <kvalita_odrazu_vody>1</kvalita_odrazu_vody>
        <kvalita_fyziky>2</kvalita_fyziky>
        <deformace_terenu>vysoka</deformace_terenu>
        <kvalita_stop_pasu>stredni</kvalita_stop_pasu>
      </detaily>
      <stiny>1</stiny>
      <detaily_pobrezi>1</detaily_pobrezi>
      <efekt_vlneni>1</efekt_vlneni>
      <detaily_vegetace>0</detaily_vegetace>
    </grafika>
    <zvuk zapnuto="1" kvalita_zvuk="vysoka">
      <hlasitost>9</hlasitost>
      <hlasitost_efektu>10</hlasitost_efektu>
      <hlasitost_motoru>10</hlasitost_motoru>
      <hlasitost_strelby>10</hlasitost_strelby>
      <hlasitost_komunikace>9</hlasitost_komunikace>
      <zvuky_v_hangaru>1</zvuky_v_hangaru>
    </zvuk>
    <rozhrani>
      <velke_pismo_menu>0</velke_pismo_menu>
      <rozhrani_s_gamepadem>0</rozhrani_s_gamepadem>  
      <barva_zamerneho_krize>zluta</barva_zamerneho_krize>
      <velikost_zamerneho_krize>0.9</velikost_zamerneho_krize>
      <filtr_konverzace>1</filtr_konverzace>
      <velikost_ukaz_poskozeni>0.6</velikost_ukaz_poskozeni>
      <velikost_takticke_mapy>0.5</velikost_takticke_mapy>
      <titulky>0</titulky>
      <predsazeni>1</predsazeni>
      <ukazatele_nepratel>1</ukazatele_nepratel>
      <zobrazeni_poskozeni>1</zobrazeni_poskozeni>
    </rozhrani>
  </prednastaveni>
  <prednastaveni id="set2">
    <hra verze="1.67.2.115" uzivatelske_jmeno="Lipa27" autolog="1">
      <jazyk>Czech</jazyk>
      <napoveda>0</napoveda>
      <jednotky_vzdalenosti>Km</jednotky_vzdalenosti>
      <jednotky_rychlosti>Km/h</jednotky_rychlosti>
      <jednotky_teploty>C</jednotky_teploty>
      <vychozi_pohled>venkovni</vychozi_pohled>
    </hra>
    <grafika rozliseni="1920x1080" mod="Fullscreen">
        <antistropni_filtr>1</antistropni_filtr>
        <vyhlazovani_hran>1</vyhlazovani_hran>
        <extra_AA>1</extra_AA>
      <detaily kvalita_det="vysoka">
        <kvalita_textur>vysoka</kvalita_textur>
        <kvalita_stinu>vysoka</kvalita_stinu>
        <vykreslovaci_rozliseni>1</vykreslovaci_rozliseni>
        <kvalita_mraku>2</kvalita_mraku>
        <kvalita_terenu>2</kvalita_terenu>
        <vzdalenost_vykreslovani>2</vzdalenost_vykreslovani>
        <kvalita_odlesku>2</kvalita_odlesku>
        <kvalita_odrazu_vody>2</kvalita_odrazu_vody>
        <kvalita_fyziky>2</kvalita_fyziky>
        <deformace_terenu>vysoka</deformace_terenu>
        <kvalita_stop_pasu>vysoka</kvalita_stop_pasu>
      </detaily>
      <stiny>1</stiny>
      <detaily_pobrezi>1</detaily_pobrezi>
      <efekt_vlneni>1</efekt_vlneni>
      <detaily_vegetace>1</detaily_vegetace>
    </grafika>
    <zvuk zapnuto="1" kvalita_zvuk="vysoka">
      <hlasitost>10</hlasitost>
      <hlasitost_efektu>10</hlasitost_efektu>
      <hlasitost_motoru>10</hlasitost_motoru>
      <hlasitost_strelby>10</hlasitost_strelby>
      <hlasitost_komunikace>9</hlasitost_komunikace>
      <zvuky_v_hangaru>1</zvuky_v_hangaru>
    </zvuk>
    <rozhrani>
      <velke_pismo_menu>0</velke_pismo_menu>
      <rozhrani_s_gamepadem>0</rozhrani_s_gamepadem>  
      <barva_zamerneho_krize>bila</barva_zamerneho_krize>
      <velikost_zamerneho_krize>1</velikost_zamerneho_krize>
      <filtr_konverzace>1</filtr_konverzace>
      <velikost_ukaz_poskozeni>0.5</velikost_ukaz_poskozeni>
      <velikost_takticke_mapy>0.7</velikost_takticke_mapy>
      <titulky>1</titulky>
      <predsazeni>1</predsazeni>
      <ukazatele_nepratel>1</ukazatele_nepratel>
      <zobrazeni_poskozeni>1</zobrazeni_poskozeni>
    </rozhrani>
  </prednastaveni>
  <prednastaveni id="set3">
    <hra verze="1.67.2.115" uzivatelske_jmeno="Tiger88" autolog="1">
      <jazyk>Russian</jazyk>
      <napoveda>0</napoveda>
      <jednotky_vzdalenosti>Km</jednotky_vzdalenosti>
      <jednotky_rychlosti>Km/h</jednotky_rychlosti>
      <jednotky_teploty>C</jednotky_teploty>
      <vychozi_pohled>venkovni</vychozi_pohled>
    </hra>
    <grafika rozliseni="800x600" mod="Fullscreen">
        <antistropni_filtr>0</antistropni_filtr>
        <vyhlazovani_hran>0</vyhlazovani_hran>
        <extra_AA>0</extra_AA>
      <detaily kvalita_det="nizka">
        <kvalita_textur>nizka</kvalita_textur>
        <kvalita_stinu>nizka</kvalita_stinu>
        <vykreslovaci_rozliseni>1</vykreslovaci_rozliseni>
        <kvalita_mraku>0.5</kvalita_mraku>
        <kvalita_terenu>0.5</kvalita_terenu>
        <vzdalenost_vykreslovani>0.3</vzdalenost_vykreslovani>
        <kvalita_odlesku>0.5</kvalita_odlesku>
        <kvalita_odrazu_vody>0</kvalita_odrazu_vody>
        <kvalita_fyziky>1</kvalita_fyziky>
        <deformace_terenu>stredni</deformace_terenu>
        <kvalita_stop_pasu>nizka</kvalita_stop_pasu>
      </detaily>
      <stiny>0</stiny>
      <detaily_pobrezi>1</detaily_pobrezi>
      <efekt_vlneni>0</efekt_vlneni>
      <detaily_vegetace>0</detaily_vegetace>
    </grafika>
    <zvuk zapnuto="1" kvalita_zvuk="stredni">
      <hlasitost>8</hlasitost>
      <hlasitost_efektu>9</hlasitost_efektu>
      <hlasitost_motoru>10</hlasitost_motoru>
      <hlasitost_strelby>10</hlasitost_strelby>
      <hlasitost_komunikace>10</hlasitost_komunikace>
      <zvuky_v_hangaru>1</zvuky_v_hangaru>
    </zvuk>
    <rozhrani>
      <velke_pismo_menu>1</velke_pismo_menu>
      <rozhrani_s_gamepadem>0</rozhrani_s_gamepadem>  
      <barva_zamerneho_krize>bila</barva_zamerneho_krize>
      <velikost_zamerneho_krize>0.5</velikost_zamerneho_krize>
      <filtr_konverzace>1</filtr_konverzace>
      <velikost_ukaz_poskozeni>0.5</velikost_ukaz_poskozeni>
      <velikost_takticke_mapy>0.5</velikost_takticke_mapy>
      <titulky>1</titulky>
      <predsazeni>1</predsazeni>
      <ukazatele_nepratel>1</ukazatele_nepratel>
      <zobrazeni_poskozeni>1</zobrazeni_poskozeni>
    </rozhrani>
  </prednastaveni>
  <prednastaveni id="set4">
    <hra verze="1.67.2.115" uzivatelske_jmeno="1pilot1" autolog="1">
      <jazyk>English</jazyk>
      <napoveda>0</napoveda>
      <jednotky_vzdalenosti>Mil</jednotky_vzdalenosti>
      <jednotky_rychlosti>Mil/h</jednotky_rychlosti>
      <jednotky_teploty>F</jednotky_teploty>
      <vychozi_pohled>kabina</vychozi_pohled>
    </hra>
    <grafika rozliseni="1600x900" mod="Okno">
        <antistropni_filtr>1</antistropni_filtr>
        <vyhlazovani_hran>1</vyhlazovani_hran>
        <extra_AA>1</extra_AA>
      <detaily kvalita_det="vysoka">
        <kvalita_textur>vysoka</kvalita_textur>
        <kvalita_stinu>stredni</kvalita_stinu>
        <vykreslovaci_rozliseni>1</vykreslovaci_rozliseni>
        <kvalita_mraku>1</kvalita_mraku>
        <kvalita_terenu>1</kvalita_terenu>
        <vzdalenost_vykreslovani>1.5</vzdalenost_vykreslovani>
        <kvalita_odlesku>1.8</kvalita_odlesku>
        <kvalita_odrazu_vody>1</kvalita_odrazu_vody>
        <kvalita_fyziky>1.5</kvalita_fyziky>
        <deformace_terenu>stredni</deformace_terenu>
        <kvalita_stop_pasu>stredni</kvalita_stop_pasu>
      </detaily>
      <stiny>1</stiny>
      <detaily_pobrezi>1</detaily_pobrezi>
      <efekt_vlneni>1</efekt_vlneni>
      <detaily_vegetace>1</detaily_vegetace>
    </grafika>
    <zvuk zapnuto="1" kvalita_zvuk="vysoka">
      <hlasitost>10</hlasitost>
      <hlasitost_efektu>10</hlasitost_efektu>
      <hlasitost_motoru>9</hlasitost_motoru>
      <hlasitost_strelby>9</hlasitost_strelby>
      <hlasitost_komunikace>10</hlasitost_komunikace>
      <zvuky_v_hangaru>1</zvuky_v_hangaru>
    </zvuk>
    <rozhrani>
      <velke_pismo_menu>0</velke_pismo_menu>
      <rozhrani_s_gamepadem>0</rozhrani_s_gamepadem>  
      <barva_zamerneho_krize>modra</barva_zamerneho_krize>
      <velikost_zamerneho_krize>0.8</velikost_zamerneho_krize>
      <filtr_konverzace>1</filtr_konverzace>
      <velikost_ukaz_poskozeni>0.7</velikost_ukaz_poskozeni>
      <velikost_takticke_mapy>0.5</velikost_takticke_mapy>
      <titulky>1</titulky>
      <predsazeni>1</predsazeni>
      <ukazatele_nepratel>1</ukazatele_nepratel>
      <zobrazeni_poskozeni>1</zobrazeni_poskozeni>
    </rozhrani>
  </prednastaveni>
  <prednastaveni id="set5">
    <hra verze="1.67.2.115" uzivatelske_jmeno="Lotr666" autolog="1">
      <jazyk>Czech</jazyk>
      <napoveda>0</napoveda>
      <jednotky_vzdalenosti>Km</jednotky_vzdalenosti>
      <jednotky_rychlosti>Km/h</jednotky_rychlosti>
      <jednotky_teploty>C</jednotky_teploty>
      <vychozi_pohled>kabina</vychozi_pohled>
    </hra>
    <grafika rozliseni="1024x768" mod="Fullscreen">
        <antistropni_filtr>1</antistropni_filtr>
        <vyhlazovani_hran>0</vyhlazovani_hran>
        <extra_AA>1</extra_AA>
